//-*-c++-*-
#pragma once

#define MESON_VERSION_MAJOR 0
#define MESON_VERSION_MINOR 1

#ifndef MESON_STRINGIFY
#define MESON_STRINGIFY(n) MESON_STRINGIFY_HELPER(n)
#define MESON_STRINGIFY_HELPER(n) #n
#endif

#define MESON_VERSION_STRING \
  MESON_STRINGIFY(MESON_VERSION_MAJOR) "." MESON_STRINGIFY(MESON_VERSION_MINOR)
